# Generated by Django 4.0.2 on 2022-03-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=250)),
                ('activity', models.IntegerField()),
                ('image', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
    ]
